---
title: "ENMPA: An R package for Ecological Niche Modeling using Presence-Absence Data"
author: "Luis F. Arias-Giraldo, Marlon E. Cobos, A. Town Peterson."
output: 
  github_document:
    toc: yes
    toc_depth: 3

---



<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>", 
                      fig.path = "man/figures/README-", out.width = "100%")
```

<!-- badges: start -->
<!-- badges: end -->

<hr>

The package `enmpa` comprises a set of tools to perform Ecological Niche Modeling
analysis, including data partitioning, model selection, calibration, fitting and evaluation.

<br>

## Installation

You can install the development version of enmpa from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("Luisagi/enmpa")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r message=FALSE}
library(enmpa)
library(terra)

# Load species occurrences and environmental data
pa_data <- read.csv(system.file("extdata", "pa_data.csv", package = "enmpa"))
env_vars <- terra::rast(system.file("extdata", "raster_vars.tif", package = "enmpa"))
```


```{r }
head(pa_data)
```

```{r }
terra::plot(env_vars)
```


### Running analyses


